### PR TITLE
55: hotfix

### LINKED ISSUE #55: Commit eaf6486 borked the code.
output of `npm run build:test`:

```
Hash: 93d8e6ee85d61a869706
Version: webpack 3.3.0
Child
    Hash: 93d8e6ee85d61a869706
    Time: 210ms
       [4] ./src/helpers.js 6.6 kB {0} [built] [1 error]
        + 4 hidden modules
    
    ERROR in ./src/helpers.js
    
    /home/david/Repos/tagprobot/src/helpers.js
      200:1  error  Line 200 exceeds the maximum line length of 100  max-len
      201:1  error  Line 201 exceeds the maximum line length of 100  max-len
      202:1  error  Line 202 exceeds the maximum line length of 100  max-len
    
    ✖ 3 problems (3 errors, 0 warnings)
    
     @ ./src/index.js 7:15-35
Hash: 0444e3af0ec33b7916fa
Version: webpack 3.3.0
Child
    Hash: 0444e3af0ec33b7916fa
    Time: 125ms
      [40] ./src/helpers.js 6.04 kB {0} [built]
        + 40 hidden modules
    
    ERROR in failed test: test getTraversableCells - should be equivalent
      Expected: [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ]
      Actual: [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ]
    
    ERROR in tests failed
```

### LINKED ISSUE #59: Trailing commas when separating function inputs to their own lines results in compiler error on `npm run build:test`
See PR #56 for details on this

### PR DESCRIPTION
**Pull request by davidabrahams**
Fixes #55 and fixes #59 

Changes

- Made lines shorter
- Previously when webpack was running tests, it was not transpiling the files it was testing. Now, it is.

### CODE REVIEW

File: src/helpers/map.js [hunk 1]
```diff
@@ -137,20 +137,19 @@ export function getTraversableCells(cpt, map) {
...
+      // spike, corner wall), the entire tile is marked as non-traversable
       const objRadius = 29;
       fillGridWithSubgrid(
         emptyCells,
         traversableCellsInTile(
           isTraversable(map[x][y]),
           cpt,
-          objRadius
-        ),
+          objRadius),
```
Comment (davidabrahams) [inline src/helpers/map.js]: @billmwong if you want thigs to be seperaionated like this, the brackets have to be at the end, or eslint complains b/c it wants a trailing comma...

File: src/helpers/map.js [hunk 2]
```diff
@@ -137,20 +137,19 @@ export function getTraversableCells(cpt, map) {
...
         x * cpt,
-        y * cpt
-      );
+        y * cpt);
```
Comment (davidabrahams) [inline src/helpers/map.js]: See comment above
